export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const GET_USER_INFOR = "GET_USER_INFOR";
export const GET_USER_INFOR_SUCCESS = "GET_USER_INFOR_SUCCESS";
export const GET_USER_INFOR_ERROR = "GET_USER_INFOR_ERROR";

export const EDIT_USER_INFORMATION = "EDIT_USER_INFORMATION";
export const EDIT_USER_INFORMATION_SUCCESS = "EDIT_USER_INFORMATION_SUCCESS";
export const EDIT_USER_INFORMATION_ERROR = "EDIT_USER_INFORMATION_ERROR";
