export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAIL = "GET_LIST_PRODUCT_FAIL";

export const DELETE_PRODUCT = " DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = " DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = " DELETE_PRODUCT_FAIL";

export const GET_SKU_OF_FRODUCT = "GET_SKU_OF_FRODUCT";
export const GET_SKU_OF_PRODUCT_SUCCESS = "GET_SKU_OF_PRODUCT_SUCCESS";
export const GET_SKU_OF_FRODUCT_FAIL = "GET_SKU_OF_FRODUCT_FAIL";

export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY";
export const GET_LIST_CATEGORY_SUCCESS = "GET_LIST_CATEGORY_SUCCESS";
export const GET_LIST_CATEGORY_FAIL = "GET_LIST_CATEGORY_FAIL";

export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL";

export const DELETE_CATEGORY = " DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = " DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = " DELETE_CATEGORY_FAIL";

export const ADD_CATEGORY = " ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = " ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = " ADD_CATEGORY_FAIL";

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL";
