export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const ADD_PRODUCT_CART_SUCCESS = "ADD_PRODUCT_CART_SUCCESS";
export const ADD_PRODUCT_CART_FAIL = "ADD_PRODUCT_CART_FAIL";

export const GET_CART_BY_USER = "GET_CART_BY_USER";
export const GET_CART_BY_USER_SUCCESS = "GET_CART_BY_USER_SUCCESS";
export const GET_CART_BY_USER_FAIL = "GET_CART_BY_USER_FAIL";
export const CLEAR_LIST_CART = "CLEAR_LIST_CART";

export const DELETE_ITEM_CART = "DELETE_ITEM_CART";
export const DELETE_ITEM_CART_SUCCESS = "DELETE_ITEM_CART_SUCCESS";
export const DELETE_ITEM_CART_FAIL = "DELETE_ITEM_CART_FAIL";

export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";
